Update filebeatclean

diff --git a/filebeatclean b/filebeatclean
--- a/filebeatclean
+++ b/filebeatclean
@@ -3,19 +3,31 @@
 # to elasticsearch. Then it waits 'till registry offset reaches file size.
 # It can be also launched by hand.
 
+#!/bin/bash
+
 if [[ "$#" < 1 ]]; then
-	echo "Usage: $0 <filebeat_registry_file>"
+	echo "Usage: $0 <registry_file>"
 	exit 1
 else
-	LFNAME=$(cat "$1" | cut -d, -f1 | cut -d: -f2 | sed 's/\"//g')
-	OFFSET=$(cat "$1" | cut -d, -f2 | cut -d: -f2)
-	LFSIZE=$(stat -c%s $LFNAME)
+	if [ -e "$1" ]; then
+		LFNAME=$(cat "$1" | cut -d, -f1 | cut -d: -f2 | sed 's/\"//g')
+		OFFSET=$(cat "$1" | cut -d, -f2 | cut -d: -f2)
+		if [ -e "$LFNAME" ]; then
+			LFSIZE=$(stat -c%s $LFNAME)
+		else
+			echo "Error: log file not found."
+			exit 1
+		fi
 
-	if [ -e $LFNAME ] && [ $OFFSET == $LFSIZE ]; then
-		echo "Flushing $LFNAME ($LFSIZE)"
-		rm "$LFNAME"
+		echo "$(date): Starting filebeat log watch"
+		if [ -e $LFNAME ] && [ $OFFSET == $LFSIZE ]; then
+			echo "$(date): Flushing $LFNAME ($LFSIZE)"
+			rm "$LFNAME"
+		else
+			sleep 30
+			exec $0 $1
+		fi
 	else
-		sleep 30
-		exec $0 $1
+		echo "Error: registry file not found."
 	fi
 fi
